[package]
name = "kachiclash"
version = "0.1.0"
authors = ["Daniel Dickison <kachiclash@danieldickison.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "1.0"
actix-identity = "0.1"
actix-session = "0.1"
actix-files = "0.1"
url = "1.7"
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1"
failure = "0.1.3"
envconfig = "0.5.0"
envconfig_derive = "0.5.0"
log = "0.4"
env_logger = "0.6.1"
chrono = "0.4"
itertools = "0.8"
oauth2 = "3.0.0-alpha.3"
result = "1.0.0"
regex = "1.3.1"
lazy_static = "1.4.0"
rand = "0.7.2"

[dependencies.rusqlite]
version = "0.19.0"
features = ["bundled", "chrono"]

[dependencies.askama]
version = "0.8"
# features = ["with-actix-web"]
